// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trzbvjpfmqjoqbezlydg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyemJ2anBmbXFqb3FiZXpseWRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NzA2NzEsImV4cCI6MjA1NTA0NjY3MX0.KbfcQleGFPSeY1YEzXFYKz3Bv4wdkAdnDly-kjhzcdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);